#!/bin/bash
#SBATCH --job-name="make_netcdf"
#SBATCH --output="make_netcdf.%j.%N.out"  
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --mem-per-cpu=2GB
#SBATCH --account=scec_608
#SBATCH --partition=main
#SBATCH --chdir=/project/scec_608/maechlin/netcdf/ucvm2netcdf
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=maechlin@usc.edu

source ~/.bashrc
python3 make_cvmh_basins_elev_nc.py
